Use momentum in l2 gas pricing
OffchainLabs/mini-compiler pull request #663
Opened 2022-01-26 03:59 UTC by edfelten

This changes the L2 gas price adjustment algorithm, to include a "momentum" term.  We use a rateEstimator abstraction to estimate the rate at which gas is being consumed, in a decaying weighted average with 60-second time constant.  

If the estimated gas usage rate is G, and the chain speed limit is S, this multiplies the L2 gas price by approximately (239+min(2, G/S))/240 each second.  The gas pool fullness measure provides an additional factor of the same magnitude, so that overall the price is multiplied by a factor between 119/120 and 121/120 each second.

The estimator's time constant (default 60 seconds) and a cap on the estimate (default 4*chainSpeedLimit) are added as chain parameters.

2022-01-27 07:51 UTC, RachelFranks requested changes
We'll need to make a minor change to bring equilibrium where we want it -- otherwise looks good (the estimator makes sense & the overall structure is solid)

2022-01-27 07:51 UTC, RachelFranks commented on arb_os/gasAccounting.mini
> +    let rateFactor = rateEstimator_get(rateEstimator) * gasPoolMax / (2 *speedLimit);
I think we should remove the `2` here

Currently we have the following
```rs
price' = price * (120 * pool_max + factor - pool) / (120 * pool_max)
where factor = min(pool_max, estimate * pool_max / (2 * speed))
```
Suppose the price is rising
```rs
price' = price * (120 * pool_max + factor - pool) / (120 * pool_max)
price' > price 
=> factor > pool 
=> min(pool_max, estimate * pool_max / (2 * speed)) > pool
=> estimate * pool_max / (2 * speed) > pool  // pool_max exceeds pool
```
As we approach the steady state, `estimate` will approximate the speed limit, so
```rs
speed * pool_max / (2 * speed) > pool
pool_max / 2 > pool
=> The pool will be half full at equilibrium
```

2022-01-27 11:01 UTC, RachelFranks commented on arb_os/gasAccounting.mini
> +    let rateFactor = rateEstimator_get(rateEstimator) * gasPoolMax / (2 *speedLimit);
Having discussed and clarified the 50% is intended to be a short-term buffer, let's finalize a constant (perhaps still 2) and then I'll approve this :)

2022-02-05 00:49 UTC, RachelFranks approved these changes
Looks great!

2022-02-05 01:38 UTC, merged

2022-02-08 04:05 UTC, hkalodner commented on arb_os/gasAccounting.mini
> +            if let Some(x) = chainParams_get(const::Atom_Param_GasPoolFullnessTargetPercent) {
Shouldn't this be `Atom_Param_PoolFullnessRatioWeightBasisPoints`

2022-02-08 04:05 UTC, hkalodner commented on arb_os/gasAccounting.mini
> +                const::Atom_Param_PoolFullnessRatioWeightBasisPoints
Shouldn't this be `Default_Param_PoolFullnessRatioWeightBasisPoints`?

2022-02-08 04:05 UTC, hkalodner commented on arb_os/gasAccounting.mini
> +                gasPoolMax / 2
Maybe better to default to `Default_Param_GasPoolFullnessTargetPercent` instead like below

2022-02-08 04:05 UTC, hkalodner commented on arb_os/gasAccounting.mini
> +            );
Maybe safer to combine these into a single function if they're always done in combination?